In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [ ]:
final_df = pd.read_csv(
    "/content/drive/MyDrive/FP_AI_2026/FinalDataset.csv"
)

print(final_df.shape)

display(final_df.head())

(1000, 5)

,problem_id,Sample_Code,Generated,Language,Source
0,Prob3353,import Java.util.*;\npublic class Main {\n\tpu...,Human,Java,CodeNet
1,Prob6275,#include <stdio.h>\n#include <string.h>\n#incl...,AI,C,ChatGPT-4
2,Prob97,import Java.util.Scanner;\n\npublic class Mood...,AI,Java,ChatGPT-4
3,Prob5190,#include <bits/stdc++.h>\nusing namespace std;...,Human,C++,CodeNet
4,Prob1082,"N,M=map(int,input().split())\nL,R=map(int,inpu...",Human,Python,CodeNet

In [ ]:
print(
    final_df.isnull().sum()
)

problem_id     0
Sample_Code    0
Generated      0
Language       0
Source         0
dtype: int64

In [ ]:
duplicate_rows = (
    final_df.duplicated()
    .sum()
)

print(
    "Duplicate Rows:",
    duplicate_rows
)

Duplicate Rows: 0

In [ ]:
duplicate_code = (
    final_df
    .duplicated(
        subset=["Sample_Code"]
    )
    .sum()
)

print(
    "Duplicate Code:",
    duplicate_code
)

Duplicate Code: 0

In [ ]:
final_df["Label"] = (
    final_df["Generated"]
    .map({
        "Human": 0,
        "AI": 1
    })
)

In [ ]:
display(
    final_df[
        [
            "Generated",
            "Label"
        ]
    ].head()
)

  Generated  Label
0     Human      0
1        AI      1
2        AI      1
3     Human      0
4     Human      0

In [ ]:
print(
    final_df["Label"]
    .value_counts()
)

Label
0    500
1    500
Name: count, dtype: int64

In [ ]:
final_df["Code_Length"] = (
    final_df["Sample_Code"]
    .astype(str)
    .apply(len)
)

display(
    final_df["Code_Length"]
    .describe()
)

count     1000.000000
mean      1110.531000
std       1447.007658
min         63.000000
25%        357.750000
50%        589.500000
75%       1196.750000
max      15334.000000
Name: Code_Length, dtype: float64

In [ ]:
X = final_df["Sample_Code"]

y = final_df["Label"]

In [ ]:
X_train,\
X_temp,\
y_train,\
y_temp = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

In [ ]:
X_val,\
X_test,\
y_val,\
y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

In [ ]:
print(
    "Train:",
    len(X_train)
)

print(
    "Validation:",
    len(X_val)
)

print(
    "Test:",
    len(X_test)
)

Train: 800
Validation: 100
Test: 100

In [ ]:
print(
    y_train.value_counts()
)

print(
    y_val.value_counts()
)

print(
    y_test.value_counts()
)

Label
1    400
0    400
Name: count, dtype: int64
Label
0    50
1    50
Name: count, dtype: int64
Label
1    50
0    50
Name: count, dtype: int64

In [ ]:
train_df = pd.DataFrame({

    "Sample_Code": X_train,

    "Label": y_train

})

val_df = pd.DataFrame({

    "Sample_Code": X_val,

    "Label": y_val

})

test_df = pd.DataFrame({

    "Sample_Code": X_test,

    "Label": y_test

})

In [ ]:
train_df.to_csv(
    "/content/drive/MyDrive/FP_AI_2026/data/train.csv",
    index=False
)

val_df.to_csv(
    "/content/drive/MyDrive/FP_AI_2026/data/val.csv",
    index=False
)

test_df.to_csv(
    "/content/drive/MyDrive/FP_AI_2026/data/test.csv",
    index=False
)

In [ ]:
print("="*50)

print(
    "FINAL DATASET"
)

print("="*50)

print(
    "Total Data:",
    len(final_df)
)

print(
    "Human:",
    (
        final_df["Label"] == 0
    ).sum()
)

print(
    "AI:",
    (
        final_df["Label"] == 1
    ).sum()
)

print(
    "Languages:",
    final_df["Language"]
    .nunique()
)

print(
    "Sources:",
    final_df["Source"]
    .nunique()
)

print(
    "Average Code Length:",
    round(
        final_df["Code_Length"]
        .mean(),
        2
    )
)

==================================================
FINAL DATASET
==================================================
Total Data: 1000
Human: 500
AI: 500
Languages: 4
Sources: 7
Average Code Length: 1110.53